runtime: java
env: flex
instance_class: F1

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "17"

handlers:
  - url: /ws
    script: auto
    secure: always
    http_headers:
      Upgrade: websocket
      Connection: Upgrade

network:
  session_affinity: true
